### ISSUE TITLE
running on HPC

### ISSUE THREAD

**Issue by Shicheng-Guo** [NBISweden/pipelines-nextflow#65]
Do you test them to run them on Slurm based HPC system? 
Thanks
Shicheng

**Comment by mahesh-panchal** [comment]
Yes. Uppmax and our own cluster both use slurm as the job queue manager. 

Please follow the instructions on how to configure the pipelines. To better understand the configuration options we provide, please read https://www.nextflow.io/docs/latest/config.html, which describes how to configure a Nextflow workflow. 
We provide two profiles that use the slurm executor; one specifically for Uppmax, and the other specifically for our annotation cluster. The profiles may be useful to you, otherwise you will need to write your own configuration profile. 
I hope that helps.
